export const ActionType =  {
    GET_ALL_PRODUCT: "GET_ALL_PRODUCT",
    ADD_TO_CART: "ADD_TO_CART",
    REMOVE_FROM_CART: "REMOVE_FROM_CART",
    REMOVE_ALL_CART: "REMOVE_ALL_CART",
    ADD_TO_WISH_LIST: "ADD_TO_WISH_LIST",
    REMOVE_FROM_WISH_LIST: "REMOVE_FROM_WISH_LIST",
    REMOVE_ALL_WISHLIST: "REMOVE_ALL_WISHLIST",
    PRODUCT_DETAIL: "PRODUCT_DETAIL",
    SEARCH_RESULT: "SEARCH_RESULT",
    REMOVE_SEARCH_RESULT: "REMOVE_SEARCH_RESULT",
    PREV_PATH: "PREV_PATH",
    SIGN_IN: "SIGN_IN",
}